service: serverless-email-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http:
          path: "{proxy+}"
          method: any

plugins:
  - serverless-offline
