service: serverless-email-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  apiKeys:
    - EmailServiceKeys
    - ${opt:stage}-EmailServiceKeys
  usagePlan:
    throttle:
      burstLimit: 1
      rateLimit: 1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http:
          path: "{proxy+}"
          method: any
          private: true

plugins:
  - serverless-offline
